name: Build Kernel Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # This enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install required dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

      # Step 3: Set up environment
      - name: Setup Environment
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-

      # Step 4: Build the kernel
      - name: Build Kernel
        run: |
          make defconfig
          make -j$(nproc)

      # Step 5: Upload build artifacts
      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dts/
