name: Build Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Nix package manager
      - name: Install Nix
        run: curl -L https://nixos.org/nix/install | sh

      # Step 3: Source Nix setup script
      - name: Source Nix
        run: . /home/runner/.nix-profile/etc/profile.d/nix.sh

      # Step 4: Set up the environment with make-env.nix
      - name: Setup Environment
        run: nix-shell make-env.nix

      # Step 5: Execute make.sh
      - name: Run make.sh
        run: ./make.sh
